---
Profiles:

    DibsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Dibs
                  
    OneOrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Dibs
                 
                              
Organizations:

    - &OrdererOrg
        Name: OrdererOrg

        ID: OrdererMSP

        MSPDir: crypto-config/ordererOrganizations/dibs.cash/msp

    - &Dibs
        Name: DibsMSP

        ID: DibsMSP

        MSPDir: crypto-config/peerOrganizations/dibs.cash/msp

        AnchorPeers:
            - Host: dibs.cash
              Port: 7051

 
Orderer: &OrdererDefaults

    OrdererType: solo

    Addresses:
        - orderer.dibs.cash:7050

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10

        AbsoluteMaxBytes: 99 MB

        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:

Application: &ApplicationDefaults

    Organizations:
